# velure-auth-chart/templates/external-secret-mongodb.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mongodb/username
    - secretKey: password
      remoteRef:
        key: mongodb/password
