// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repositories/interfaces.go -destination=internal/mocks/mock_repositories.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "velure-auth-service/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepositoryInterface) Create(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryInterfaceMockRecorder) Create(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Create), user)
}

// Delete mocks base method.
func (m *MockUserRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockUserRepositoryInterface) GetAll() ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetAll))
}

// GetByEmail mocks base method.
func (m *MockUserRepositoryInterface) GetByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByEmail), email)
}

// GetByID mocks base method.
func (m *MockUserRepositoryInterface) GetByID(id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByID), id)
}

// GetByPage mocks base method.
func (m *MockUserRepositoryInterface) GetByPage(page, pageSize int) ([]models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPage", page, pageSize)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByPage indicates an expected call of GetByPage.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByPage(page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPage", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByPage), page, pageSize)
}

// Update mocks base method.
func (m *MockUserRepositoryInterface) Update(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryInterfaceMockRecorder) Update(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Update), user)
}

// CountUsers mocks base method.
func (m *MockUserRepositoryInterface) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserRepositoryInterfaceMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CountUsers), ctx)
}

// MockSessionRepositoryInterface is a mock of SessionRepositoryInterface interface.
type MockSessionRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryInterfaceMockRecorder is the mock recorder for MockSessionRepositoryInterface.
type MockSessionRepositoryInterfaceMockRecorder struct {
	mock *MockSessionRepositoryInterface
}

// NewMockSessionRepositoryInterface creates a new mock instance.
func NewMockSessionRepositoryInterface(ctrl *gomock.Controller) *MockSessionRepositoryInterface {
	mock := &MockSessionRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepositoryInterface) EXPECT() *MockSessionRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepositoryInterface) Create(session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryInterfaceMockRecorder) Create(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepositoryInterface)(nil).Create), session)
}

// Delete mocks base method.
func (m *MockSessionRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepositoryInterface)(nil).Delete), id)
}

// GetByRefreshToken mocks base method.
func (m *MockSessionRepositoryInterface) GetByRefreshToken(refreshToken string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRefreshToken", refreshToken)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRefreshToken indicates an expected call of GetByRefreshToken.
func (mr *MockSessionRepositoryInterfaceMockRecorder) GetByRefreshToken(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRefreshToken", reflect.TypeOf((*MockSessionRepositoryInterface)(nil).GetByRefreshToken), refreshToken)
}

// GetByUserID mocks base method.
func (m *MockSessionRepositoryInterface) GetByUserID(userID uint) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSessionRepositoryInterfaceMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSessionRepositoryInterface)(nil).GetByUserID), userID)
}

// InvalidateByRefreshToken mocks base method.
func (m *MockSessionRepositoryInterface) InvalidateByRefreshToken(refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByRefreshToken", refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByRefreshToken indicates an expected call of InvalidateByRefreshToken.
func (mr *MockSessionRepositoryInterfaceMockRecorder) InvalidateByRefreshToken(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByRefreshToken", reflect.TypeOf((*MockSessionRepositoryInterface)(nil).InvalidateByRefreshToken), refreshToken)
}

// CountActiveSessions mocks base method.
func (m *MockSessionRepositoryInterface) CountActiveSessions(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveSessions", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveSessions indicates an expected call of CountActiveSessions.
func (mr *MockSessionRepositoryInterfaceMockRecorder) CountActiveSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveSessions", reflect.TypeOf((*MockSessionRepositoryInterface)(nil).CountActiveSessions), ctx)
}

// Update mocks base method.
func (m *MockSessionRepositoryInterface) Update(session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepositoryInterfaceMockRecorder) Update(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepositoryInterface)(nil).Update), session)
}

// MockPasswordResetRepositoryInterface is a mock of PasswordResetRepositoryInterface interface.
type MockPasswordResetRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPasswordResetRepositoryInterfaceMockRecorder is the mock recorder for MockPasswordResetRepositoryInterface.
type MockPasswordResetRepositoryInterfaceMockRecorder struct {
	mock *MockPasswordResetRepositoryInterface
}

// NewMockPasswordResetRepositoryInterface creates a new mock instance.
func NewMockPasswordResetRepositoryInterface(ctrl *gomock.Controller) *MockPasswordResetRepositoryInterface {
	mock := &MockPasswordResetRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPasswordResetRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetRepositoryInterface) EXPECT() *MockPasswordResetRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetRepositoryInterface) Create(passwordReset *models.PasswordReset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", passwordReset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetRepositoryInterfaceMockRecorder) Create(passwordReset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetRepositoryInterface)(nil).Create), passwordReset)
}

// Delete mocks base method.
func (m *MockPasswordResetRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasswordResetRepositoryInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasswordResetRepositoryInterface)(nil).Delete), id)
}

// GetByToken mocks base method.
func (m *MockPasswordResetRepositoryInterface) GetByToken(token string) (*models.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", token)
	ret0, _ := ret[0].(*models.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockPasswordResetRepositoryInterfaceMockRecorder) GetByToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockPasswordResetRepositoryInterface)(nil).GetByToken), token)
}
