---
- name: Instalar dependências necessárias
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Criar diretório /etc/apt/keyrings se não existir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Adicionar chave GPG do Kubernetes
  ansible.builtin.command:
    cmd: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Adicionar repositório do Kubernetes
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
    state: present
    update_cache: yes

- name: Atualizar o cache do APT após adicionar o repositório
  apt:
    update_cache: yes

- name: Instalar pacotes do Kubernetes
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Manter as versões dos pacotes do Kubernetes
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: hold

- name: Inicializar o cluster Kubernetes
  command: kubeadm init --apiserver-advertise-address=192.168.56.10 --pod-network-cidr=10.32.0.0/12
  args:
    creates: /etc/kubernetes/admin.conf

- name: Configurar o kubectl para o usuário vagrant
  become_user: vagrant
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Instalar rede de pods (Weave Net)
  shell: |
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
