- name: Hold Kubernetes packages to prevent updates
  become: yes
  command: apt-mark hold kubelet kubeadm kubectl

- name: Initialize Kubernetes cluster
  command: kubeadm init --apiserver-advertise-address=192.168.56.10 --pod-network-cidr=192.168.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Configure kubectl for vagrant user
  become: true
  shell: |
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config

- name: Create a token for join
  command: kubeadm token create --print-join-command
  register: join_command
  become: yes

- name: Save the join command
  copy:
    content: "{{ join_command.stdout }}"
    dest: /home/vagrant/join_command.sh
    owner: vagrant
    group: vagrant
    mode: '0755'
  become: yes

- name: Install pod network (Calico)
  become_user: vagrant
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
