---
- name: Atualizar o cache do APT
  apt:
    update_cache: yes

- name: Instalar dependências necessárias
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Adicionar chave GPG do Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adicionar repositório do Kubernetes
  apt_repository:
    repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: 'kubernetes.list'

- name: Atualizar o cache do APT após adicionar o repositório
  apt:
    update_cache: yes

- name: Instalar pacotes do Kubernetes
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Manter as versões dos pacotes do Kubernetes
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: hold

- name: Desativar swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remover entrada de swap do fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '# \1'

- name: Obter o comando de join do mestre
  shell: kubeadm token create --print-join-command
  args:
    executable: /bin/bash
  delegate_to: kube-master
  register: kubeadm_join_cmd

- name: Executar o comando de join
  command: "{{ kubeadm_join_cmd.stdout }}"
