- name: Define hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: ^127\.0\.1\.1
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: Restart hostname service
  service:
    name: hostname
    state: restarted
  when: ansible_facts['hostname'] != inventory_hostname

- name: Reset kubeadm
  command: kubeadm reset -f
  ignore_errors: yes

- name: Remove kubelet.conf if exists
  file:
    path: /etc/kubernetes/kubelet.conf
    state: absent

- name: Remove ca.crt if exists
  file:
    path: /etc/kubernetes/pki/ca.crt
    state: absent

- name: Install lsof
  apt:
    name: lsof
    state: present
  become: yes

- name: Stop kubelet service
  service:
    name: kubelet
    state: stopped
  become: yes

- name: Verify if port 10250 is in use
  shell: lsof -i :10250
  register: port_usage
  ignore_errors: yes

- name: Kill the process using port 10250
  shell: lsof -t -i :10250 | xargs kill -9
  when: port_usage.rc == 0
  become: yes

- name: Disable kubelet service
  systemd:
    name: kubelet
    enabled: no
  become: yes

- name: Restart kubelet service
  service:
    name: kubelet
    state: restarted
  become: yes

- name: Wait for master node
  wait_for:
    host: 192.168.56.10
    port: 6443
    timeout: 300

- name: Get the content of the master join command
  slurp:
    src: /home/vagrant/join_command.sh
  delegate_to: kube-master
  register: join_command_content
  run_once: true

- name: Save the join command in the worker node
  copy:
    content: "{{ join_command_content.content | b64decode }}"
    dest: /tmp/join_command.sh
    mode: '0755'

- name: Execute the join command
  command: bash /tmp/join_command.sh
