services:
  postgres:
    image: postgres
    container_name: postgres_auth_service
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - postgres_auth_network
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"

  velure-auth-service:
    build: .
    container_name: velure-auth-service
    env_file:
      - .env
    networks:
      - auth_service_network
      - postgres_auth_network
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    command: sh -c "prisma migrate dev && prisma generate && node dist/main"

networks:
  postgres_auth_network:
  auth_service_network:
    external: true
      
volumes:
  postgres_auth_data: