apiVersion: v1
kind: Service
metadata:
  name: velure-process-order
  labels:
    app: velure-process-order
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: velure-process-order
