apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: velure-publish-order-pdb
  namespace: {{ .Values.namespace | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: velure-publish-order
