apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: velure-product-deny-all
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
