{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.allow.ingressFromIngressController }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: velure-product-allow-from-ingress
spec:
  podSelector:
    matchLabels:
      {{- include "velure-product-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
