apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: velure-product-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
