apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
data:
  password: {{ .Values.mongodb.password | b64enc }}
  username: {{ .Values.mongodb.username | b64enc }}
  database: {{ .Values.mongodb.database | b64enc }}