- name: Update APT cache
  apt:
    update_cache: yes

- name: Install basic packages
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg
      - containerd
    state: present

- name: Create default configuration for containerd
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: Configure kernel parameters for Kubernetes
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Apply kernel configurations
  command: sysctl --system

- name: Get Kubernetes package key
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /usr/share/keyrings/kubernetes-apt-keyring.gpg

- name: Install Kubernetes repository
  apt_repository:
    filename: kubernetes
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /

- name: Install Kubernetes packages
  package: name={{ item }} state=present force=yes install_recommends=no
  loop: "{{ k8s_packages }}"

- name: Verify Kubernetes repository content
  command: cat /etc/apt/sources.list.d/kubernetes.list
  register: kubernetes_repo_content
  ignore_errors: yes

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: ^(.*swap.*)$
    replace: '# \1'

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter module is loaded on boot
  lineinfile:
    path: /etc/modules
    line: br_netfilter
