# Define o número de réplicas para o Deployment
replicaCount: 1
namespace: authentication

# Configuração da imagem do Docker
image:
  repository: icl00ud/velure-auth-service
  pullPolicy: IfNotPresent
  tag: "latest"

# Segredos para repositórios privados (opcional, vazio para públicos)
imagePullSecrets: []

# Sobrescrever nomes padrão
nameOverride: ""
fullnameOverride: ""

# Configurações da conta de serviço
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Anotações e rótulos personalizados para pods
podAnnotations: {}
podLabels: {}

# Contexto de segurança do Pod
podSecurityContext: {}
securityContext: {}

# Configurações do serviço (ClusterIP expõe o serviço internamente)
service:
  type: ClusterIP
  port: 3020

# Configuração de Ingress (desativado por enquanto)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: auth.velure.local # Ajuste conforme necessário
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Recursos de CPU e memória para o container
resources:
  limits:
    cpu: "150m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

# Probes de liveness e readiness
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Configuração de autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 65

# Volumes adicionais (se necessário)
volumes: []
volumeMounts: []

# Seletores e tolerâncias para nós
nodeSelector: {}
tolerations: []
affinity: {}
