apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: velure-auth-deny-all
  namespace: {{ .Values.namespace | quote }}
spec:
  podSelector:
    matchLabels:
      app: velure-auth
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
