{
 "title": "GoFr - Application Services Monitoring",
 "description": "Gofr Dashboard offers real-time insights into our system's performance, displaying key metrics like response times and error rates. Tailored for DevOps and engineering teams, it pulls data from Prometheus and Kubernetes. Updated regularly, we encourage your feedback to make it even more valuable for your needs.",
 "tags": [ "Observability Common" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "prometheus" },
   { "name": "Service", "query": { "query": "label_values(app_name)" } }
  ]
 },
 "panels": [
  { "title": "App Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "targets": [
    { "expr": "app_info{app_name='$Service'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Framework Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 1 },
   "targets": [
    { "expr": "app_info{app_name='$Service'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "targets": [
    { "expr": "go_info{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (app_go_routines{})",
     "legendFormat": "__auto"
    },
    { "expr": "sum(app_go_routines{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (app_sys_memory_alloc{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time SLA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_http_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": " 90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_http_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_http_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99.9"
    }
   ]
  },
  {
   "title": "Request Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(app_http_response_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (path, method) (\n  increase(app_http_response_count{}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Code Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(app_http_response_count{}[$__rate_interval])\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Route Level SLA",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_http_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_http_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_http_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    }
   ]
  },
  {
   "title": "Route Level Response Code",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(path,method)(increase(app_http_response_count{status=\"400\"}[$__range]))",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_response_count{status=\"401\"}[$__range]))",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_response_count{status=\"403\"}[$__range]))",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_response_count{status=\"404\"}[$__range]))",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_response_count{status=~\"5.+\"}[$__range]))",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_response_count{status=~\"2.+\"}[$__range]))",
     "legendFormat": "{{path}} {{method}}"
    }
   ]
  },
  {
   "title": "Outbound Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time SLA",
   "type": "timeseries",
   "description": "Outbound request level 99%ile response time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_http_service_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_service_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_http_service_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_http_service_response_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99.9"
    }
   ]
  },
  {
   "title": "Request Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(app_http_service_response_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (path, method) (\n  increase(app_http_service_response_count{}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Code Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(app_http_service_response_count{}[$__rate_interval])\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Route Level SLA",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_http_service_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_service_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_http_service_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_http_service_response_bucket{}[$__range])) by (le, path,method)) * 1000",
     "legendFormat": "{{path}} {{method}}"
    }
   ]
  },
  {
   "title": "Route Level Response Code",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum by(path,method)(increase(app_http_service_response_count{}[$__range]))",
     "legendFormat": "Verbose"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_service_response_count{}[$__range]))"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_service_response_count{}[$__range]))"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_service_response_count{}[$__range]))"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_service_response_count{}[$__range]))"
    },
    {
     "expr": "sum by(path,method)(increase(app_http_service_response_count{}[$__range]))"
    }
   ]
  },
  {
   "title": "SQL Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time SLA",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_sql_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_sql_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_sql_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_sql_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Query Count over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(app_sql_stats_count{}[$__rate_interval]))",
     "legendFormat": "{{type}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_sql_inUse_connections{}", "legendFormat": "InUse" },
    { "expr": "app_sql_open_connections{}", "legendFormat": "Open" }
   ]
  },
  {
   "title": "Query Type Level SLA",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_sql_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_sql_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_sql_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_sql_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time SLA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_redis_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_redis_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_redis_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_redis_stats_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Query Count over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(app_redis_stats_bucket{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Type Level SLA",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_redis_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_redis_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_redis_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(app_redis_stats_bucket{}[$__range])) by (le,type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PubSub Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "app_pubsub_subscribe_total_count_total{}"
    }
   ]
  },
  {
   "title": "Consumption Over Time (Receive)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (increase(app_pubsub_subscribe_total_count_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (increase(app_pubsub_subscribe_total_count_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption Over Time (Success)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (increase(app_pubsub_subscribe_success_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (increase(app_pubsub_subscribe_success_count_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption Over Time (Failure)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (\n   increase(app_pubsub_subscribe_total_count_total{}[$__rate_interval])\n)\n-\nsum by (topic) (\n   increase(app_pubsub_subscribe_success_count_total{}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (\n  increase(app_pubsub_subscribe_total_count_total{}[$__rate_interval])\n)\n-\nsum (\n  increase(app_pubsub_subscribe_success_count_total{}[$__rate_interval])\n)",
     "legendFormat": "Total Failure"
    }
   ]
  },
  {
   "title": "PubSub Publisher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_pubsub_publish_total_count_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish Over Time (Total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (increase(app_pubsub_publish_total_count_total{}[$__rate_interval]))",
     "legendFormat": "{{topic}}({{consumerGroup}})"
    },
    {
     "expr": "sum (increase(app_pubsub_publish_total_count_total{}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Publish Over Time (Success)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (\n   increase(app_pubsub_publish_success_count_total{}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n  increase(app_pubsub_publish_success_count_total{}[$__rate_interval])\n)",
     "legendFormat": "Total Success"
    }
   ]
  },
  {
   "title": "Publish Over Time (Failure)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (\n   increase(app_pubsub_publish_total_count_total{}[$__rate_interval])\n)\n-\nsum by (topic) (\n   increase(app_pubsub_publish_success_count_total{}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (\n  increase(app_pubsub_publish_total_count_total{}[$__rate_interval])\n)\n-\nsum (\n  increase(app_pubsub_publish_success_count_total{}[$__rate_interval])\n)",
     "legendFormat": "Total Failure"
    }
   ]
  }
 ]
}