apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: datastores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
        - name: MONGO_INITDB_DATABASE
          value: "velure"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: datastores
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: datastores
type: Opaque
data:
  mongodb-root-password: cm9vdA==
  mongodb-passwords: dmVsdXJlMTIz