services:
  velure-product-service:
    build: .
    container_name: velure-product-service
    env_file:
      - .env
    networks:
      - product_service_network
    ports:
      - "3010:3010"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: velure_user
      MONGO_INITDB_ROOT_PASSWORD: velure_password
      MONGO_INITDB_DATABASE: velure_database
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - product_service_network

  redis:
    image: redis
    container_name: redis-products
    restart: always
    ports:
      - "6379:6379"
    networks:
      - product_service_network

networks:
  product_service_network:
    external: true

volumes:
  mongodb_data: