replicaCount: 2
image:
  repository: icl00ud/velure-publish-order
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3030
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 65
order:
  exchange: orders
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

secrets:
  create: true
  rabbitmq:
    url: "amqp://admin:admin@rabbitmq.datastores.svc.cluster.local:5672/"
  postgres:
    url: "postgresql://postgres:postgres@postgresql.datastores.svc.cluster.local:5432/velure"
