services:
  velure-order-service:
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
      - TRACE_EXPORTER=gofr
      - TRACER_RATIO=0.1
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "8000:8000"
      - "2121:2121"
    depends_on:
      - grafana
      - prometheus
      - rabbitmq
    restart: always
    networks:
      - gofr-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - gofr-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - gofr-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ_HOST}
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - gofr-network

networks:
  gofr-network:
