name: Angular

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-20.04', 'ubuntu-18.04' ]
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: ng build --configuration=production

    - name: Message output
      run: echo "Application builded"
