name: Build Angular App

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        node_version: [ 20 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Angular app
      run: npm run build --if-present
