name: Build Angular App

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'ubuntu-20.04', 'ubunt-18.04' ]
        node_version: [ 20 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Angular app
      run: npm run build --if-present

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/velure-ui-service:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/velure-ui-service:latest
